version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/other
    #   - /opt/nginx/ssl:/ssl
    links:
      - server-koa
      - web
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes: 
      - ~/data/db:/data/db
  server-koa:
    build: ./koa-server
    container_name: server-koa
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    # command: start
    volumes:
      - ./koa-server:/server
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - server-koa
      - mongodb
    volumes:
      - ./web:/web
